import { Badge } from '@/components/ui/badge';
import { Card, CardDescription, CardTitle } from '@/components/ui/card';
import { getOpenbbOverview } from '@/lib/data/openbb-repository';

function rowCountLabel(value: number | null): string {
  if (value === null) {
    return 'missing';
  }
  return value.toLocaleString();
}

export default async function OpenbbPage() {
  const overview = await getOpenbbOverview();
  const provider = overview.source.provider ?? 'not configured';
  const refreshStatus = overview.source.status ?? 'unknown';
  const sourceBadge: 'positive' | 'warning' | 'negative' =
    refreshStatus === 'fresh' ? 'positive' : refreshStatus === 'stale' ? 'warning' : 'negative';

  return (
    <div className="space-y-4">
      <Card className="border-accent/45 bg-panel-strong">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <CardTitle>OpenBB Data Backbone</CardTitle>
            <CardDescription className="mt-1">
              Live ingestion status and model wiring for the weekly signal pipeline.
            </CardDescription>
          </div>
          <Badge variant={sourceBadge}>{refreshStatus}</Badge>
        </div>

        <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
          <div className="border border-border bg-panel p-3">
            <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">Provider</p>
            <p className="mt-1 text-sm font-semibold">{provider}</p>
          </div>
          <div className="border border-border bg-panel p-3">
            <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">Refresh Mode</p>
            <p className="mt-1 text-sm font-semibold">{overview.source.mode ?? 'unknown'}</p>
          </div>
          <div className="border border-border bg-panel p-3">
            <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">Last Refresh (UTC)</p>
            <p className="mt-1 text-sm font-semibold">{overview.source.lastRefreshAt ?? 'not available'}</p>
          </div>
          <div className="border border-border bg-panel p-3">
            <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">Latest Market Date</p>
            <p className="mt-1 text-sm font-semibold">{overview.source.latestMarketDate ?? 'not available'}</p>
          </div>
        </div>
      </Card>

      <section className="grid gap-4 xl:grid-cols-[1.4fr_1fr]">
        <Card>
          <CardTitle>Snapshot Artifacts</CardTitle>
          <CardDescription className="mt-1">Files generated by OpenBB refresh and used by model tooling.</CardDescription>

          <div className="mt-4 overflow-x-auto border border-border">
            <table className="w-full text-left text-sm">
              <thead className="bg-panel-strong font-mono text-[10px] uppercase tracking-[0.12em] text-muted">
                <tr>
                  <th className="px-4 py-3">Artifact</th>
                  <th className="px-4 py-3">Rows</th>
                  <th className="px-4 py-3">Path</th>
                </tr>
              </thead>
              <tbody>
                {overview.snapshots.map((snapshot) => (
                  <tr key={snapshot.path} className="border-t border-border/70 bg-panel">
                    <td className="px-4 py-3">{snapshot.name}</td>
                    <td className="px-4 py-3 font-mono">{rowCountLabel(snapshot.rows)}</td>
                    <td className="px-4 py-3 font-mono text-xs text-slate-300">{snapshot.path}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        <Card className="space-y-4">
          <CardTitle>Model Influence</CardTitle>
          <CardDescription className="mt-1">
            Confirms whether current weekly model is trained from OpenBB dataset and features.
          </CardDescription>

          <div className="space-y-3 text-sm text-slate-200">
            <div className="border border-border bg-panel-strong p-3">
              <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">OpenBB wired into model</p>
              <p className="mt-1 font-semibold">{overview.modelIntegration.enabled ? 'Yes' : 'No'}</p>
            </div>
            <div className="border border-border bg-panel-strong p-3">
              <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">Data source</p>
              <p className="mt-1 font-semibold">{overview.modelIntegration.dataSource ?? 'unknown'}</p>
            </div>
            <div className="border border-border bg-panel-strong p-3">
              <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">Training data file</p>
              <p className="mt-1 font-mono text-xs text-slate-300">{overview.modelIntegration.dataFile ?? 'unknown'}</p>
            </div>
            <div className="border border-border bg-panel-strong p-3">
              <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">Feature set</p>
              <p className="mt-1 font-semibold">{overview.modelIntegration.featureSetVersion ?? 'unknown'}</p>
              <p className="mt-1 text-xs text-muted">
                {overview.modelIntegration.openbbFeatureCount} OpenBB-driven features /{' '}
                {overview.modelIntegration.featureCount} total
              </p>
            </div>
          </div>
        </Card>
      </section>

      <Card>
        <CardTitle>Symbol Universe</CardTitle>
        <CardDescription className="mt-1">Configured OpenBB symbols by market bucket.</CardDescription>

        <div className="mt-4 grid gap-3 md:grid-cols-3">
          <div className="border border-border bg-panel-strong p-3">
            <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">Index</p>
            <p className="mt-2 font-mono text-xs text-slate-300">{overview.symbols.index.join(', ') || 'none'}</p>
          </div>
          <div className="border border-border bg-panel-strong p-3">
            <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">HK Basket</p>
            <p className="mt-2 font-mono text-xs text-slate-300">{overview.symbols.equity.join(', ') || 'none'}</p>
          </div>
          <div className="border border-border bg-panel-strong p-3">
            <p className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">FX</p>
            <p className="mt-2 font-mono text-xs text-slate-300">{overview.symbols.currency.join(', ') || 'none'}</p>
          </div>
        </div>
      </Card>
    </div>
  );
}
