import pandas as pd
import numpy as np
import joblib
import torch
import matplotlib.pyplot as plt
from src.config import SCALER_PATH

def add_technical_indicators(df):
    """
    Adds technical indicators to the dataframe.
    """
    df = df.copy()
    
    # 1. Moving Averages
    df['MA_5'] = df['Close'].rolling(window=5).mean()
    df['MA_10'] = df['Close'].rolling(window=10).mean()
    df['MA_20'] = df['Close'].rolling(window=20).mean()
    df['MA_50'] = df['Close'].rolling(window=50).mean()

    # 2. RSI (Relative Strength Index)
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    df['RSI'] = 100 - (100 / (1 + rs))

    # 3. Price Change
    df['Price_Change'] = df['Close'].pct_change()

    # 4. Volume Change
    df['Volume_Change'] = df['Volume'].pct_change()

    # 5. Volatility (Standard Deviation of returns)
    df['Volatility'] = df['Close'].pct_change().rolling(window=20).std()

    # Fill NaNs generated by rolling windows
    df.fillna(0, inplace=True)
    
    return df

def load_scaler(scaler_name):
    """Load a saved scaler from disk"""
    path = f"{SCALER_PATH}{scaler_name}.pkl"
    try:
        return joblib.load(path)
    except FileNotFoundError:
        raise FileNotFoundError(f"Scaler not found at {path}. Run train.py first.")

def create_sequences(features, targets, seq_len):
    """
    Creates sequences for LSTM/Transformer training.
    """
    xs, ys = [], []
    for i in range(len(features) - seq_len):
        x = features[i:(i + seq_len)]
        y = targets[i + seq_len]
        xs.append(x)
        ys.append(y)
    return np.array(xs), np.array(ys)

def plot_training_loss(train_losses, val_losses):
    """Plot training and validation loss history"""
    plt.figure(figsize=(10, 6))
    plt.plot(train_losses, label='Training Loss')
    plt.plot(val_losses, label='Validation Loss')
    plt.title('Model Training History')
    plt.xlabel('Epoch')
    plt.ylabel('Loss (MSE)')
    plt.legend()
    plt.grid(True)
    return plt
